version: '3.8'

services:
  backend:
    build:
      context: ./api
    ports:
      - "5001:5000"  # Map backend port 5000
    volumes:
      - ./api:/app   # Enable live reload for development
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./ve
    ports:
      - "3000:80"    # Map frontend port 80 to localhost:3000
    depends_on:
      - backend